### ISSUE TITLE
Dependencies don't contain some crucial packages

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-lint#6]
At least `jshint-reporter-jscs` is needed as a normal dependency.

**Comment by Reinmar** [comment]
:OOOO. This is so bloody weird that I don't know what to say:


```
(t/6 0c6f145 M1) p@m /www/ckeditor5/ckeditor5-dev-lint> gulp lint
(node:50447) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[22:36:04] Using gulpfile /www/ckeditor5/ckeditor5-dev-lint/gulpfile.js
[22:36:04] Starting 'lint'...
[22:36:06] Finished 'lint' after 1.55 s
(t/6 0c6f145) p@m /www/ckeditor5/ckeditor5-dev-lint> git diff
diff --git a/package.json b/package.json
index 394ac37..61845e7 100644
--- a/package.json
+++ b/package.json
@@ -11,14 +11,14 @@
     "gulp-filter": "^4.0.0",
     "gulp-jscs": "^4.0.0",
     "gulp-jshint": "^2.0.1",
-    "gulp-util": "^3.0.7"
+    "gulp-util": "^3.0.7",
+    "jshint": "^2.9.2",
   },
   "devDependencies": {
     "chai": "^3.5.0",
     "gulp-istanbul": "^1.0.0",
     "gulp-mocha": "^2.2.0",
     "guppy-pre-commit": "^0.3.0",
-    "jshint": "^2.9.2",
     "jshint-reporter-jscs": "^0.1.0",
     "mockery": "^1.7.0",
     "sinon": "^1.17.4",
(t/6 0c6f145 M1) p@m /www/ckeditor5/ckeditor5-dev-lint> gulp lint
(node:50519) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[22:36:21] Using gulpfile /www/ckeditor5/ckeditor5-dev-lint/gulpfile.js
[22:36:21] Starting 'lint'...
[22:36:21] 'lint' errored after 19 ms
[22:36:21] Error: Unable to load JSCS config file
Unable to load JSCS config file
    at Object.parseError (/www/ckeditor5/ckeditor5-dev-lint/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/www/ckeditor5/ckeditor5-dev-lint/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/www/ckeditor5/ckeditor5-dev-lint/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/www/ckeditor5/ckeditor5-dev-lint/node_modules/jscs/lib/cli-config.js:81:27)
    at Object.<anonymous> (/www/ckeditor5/ckeditor5-dev-lint/node_modules/jscs/lib/cli-config.js:142:31)
    at /www/ckeditor5/ckeditor5-dev-lint/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/www/ckeditor5/ckeditor5-dev-lint/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/www/ckeditor5/ckeditor5-dev-lint/node_modules/jscs/lib/cli-config.js:140:9)
    at module.exports (/www/ckeditor5/ckeditor5-dev-lint/node_modules/gulp-jscs/index.js:16:27)
```

How can moving JSHint from depDeps to normal deps break JSCS?

**Comment by Reinmar** [comment]
OK, nvmnd, turns out that a syntax error in package.json caused this error... WAT?!

**Comment by Reinmar** [comment]
I also found out that gulp-mocha and gulp-istanbul can be simplified to mocha and istanbul.

**Comment by maxbarnas** [comment]
> I also found out that gulp-mocha and gulp-istanbul can be simplified to mocha and istanbul.
Seems counterintuitive. I would say it is the other way around.

**Comment by Reinmar** [comment]
They are not used any more as gulp packages. They are now used directly through npm scripts.
